version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.18.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: next
    versions:
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 9.5.4
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.1.0
    - 5.1.2
    - 5.2.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: polished
    versions:
    - 4.1.0
  - dependency-name: styled-components
    versions:
    - 5.2.1
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
  - dependency-name: eslint
    versions:
    - 7.18.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: prettier
    versions:
    - 2.2.1
