version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    ports:
        - "5432:5432"

