version: '3'
services:
  postgres:
    image: postgres
    container_name: wongames-api
    restart: always
    environment:
      POSTGRES_DB: wongames
      POSTGRES_USER: wongames
      POSTGRES_PASSWORD: wongames123
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    ports:
        - "5432:5432"

