version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: wongames123
      POSTGRES_USER: wongames
      POSTGRES_DB: wongames3
    volumes:
      - ./data:/var/lib/postgresql/data